---

- name: "Configure: Create configuration {{ integrity_config_file }}"
  ansible.builtin.template:
    src: integrity.config.j2
    dest: "{{ integrity_config_file }}"
    owner: "{{ integrity_config_file_owner }}"
    group: "{{ integrity_config_file_group }}"
    mode: "{{ integrity_config_file_mode }}"
    backup: "{{ integrity_backup_conf }}"
  loop: "{{ integrity_config_items }}"

- name: "Configure: Create directory for clients {{ integrity_linkdir }}"
  ansible.builtin.file:
    state: directory
    path: "{{ integrity_linkdir }}"
    owner: "{{ integrity_owner }}"
    group: "{{ integrity_group }}"
    mode: "{{ integrity_dir_mode }}"

- name: "Configure: Create directory for data {{ integrity_metadir }}"
  ansible.builtin.file:
    state: directory
    path: "{{ integrity_metadir }}"
    owner: "{{ integrity_owner }}"
    group: "{{ integrity_group }}"
    mode: "{{ integrity_dir_mode }}"

- name: "Configure: Create exclude files"
  ansible.builtin.template:
    src: client.exclude.j2
    dest: "{{ integrity_metadir }}/{{ item.link }}.{{ integrity_config_extexclude }}"
    owner: "{{ integrity_config_file_owner }}"
    group: "{{ integrity_config_file_group }}"
    mode: "{{ integrity_config_file_mode }}"
    backup: "{{ integrity_backup_conf }}"
  loop: "{{ integrity_exclude }}"
  loop_control:
    label: "{{ item.link }}"

- name: "Configure: Create mtreekeys files"
  ansible.builtin.template:
    src: client.mtreekeys.j2
    dest: "{{ integrity_metadir }}/{{ item.link }}.{{ integrity_config_extmtreekeys }}"
    owner: "{{ integrity_config_file_owner }}"
    group: "{{ integrity_config_file_group }}"
    mode: "{{ integrity_config_file_mode }}"
    backup: "{{ integrity_backup_conf }}"
  loop: "{{ integrity_mtreekeys }}"

- name: "Configure: Create symbolic links to clients"
  ansible.builtin.file:
    state: link
    src: "{{ item.dir }}"
    dest: "{{ integrity_linkdir }}/{{ item.link }}"
    force: true
  loop: "{{ integrity_clients }}"
  notify: Create missing meta data

# EOF
...
