---

- name: "cron: Configure cron MAILTO={{ integrity_cron_mailto }}"
  cronvar:
    name: "MAILTO"
    value: "{{ integrity_cron_mailto }}"
    user: "{{ integrity_cron_user }}"

- name: "cron: Configure cron files integrity check"
  cron:
    name: "check integrity of file"
    minute: "{{ integrity_cron_minute }}"
    hour: "{{ integrity_cron_hour }}"
    job: "{{ integrity_cron_command }}"
    user: "{{ integrity_cron_user }}"

# EOF
...
