---

- name: "Cron: Configure cron MAILTO={{ integrity_cron_mailto }}"
  community.general.cronvar:
    name: MAILTO
    value: "{{ integrity_cron_mailto }}"
    user: "{{ integrity_cron_user }}"

- name: "Cron: Configure cron files integrity check"
  ansible.builtin.cron:
    name: check integrity of file
    minute: "{{ integrity_cron_minute }}"
    hour: "{{ integrity_cron_hour }}"
    job: "{{ integrity_cron_command }}"
    user: "{{ integrity_cron_user }}"

# EOF
...
