---

- name: Add {{ansible_os_family}} specific variables
  include_vars: "{{ansible_os_family}}.yml"
  tags:
    - integrity_variables
    - integrity_all

- include: packages.yml
  tags:
    - integrity_packages
    - integrity_all

- include: source.yml
  tags:
    - integrity_source
    - integrity_all

- include: copy.yml
  tags:
    - integrity_copy
    - integrity_all

- include: configure.yml
  tags:
    - integrity_configure
    - integrity_all

- include: cron.yml
  tags:
    - integrity_cron
    - integrity_all

# EOF
...
