---

- include: packages.yml
  tags: [packages, integrity_all]

- include: source.yml
  tags: [source, integrity_all]

- include: copy.yml
  tags: [copy, integrity_all]

- include: configure.yml
  tags: [configure, integrity_all]

- include: copy_exclude_file.yml
  tags: [copy_exclude_file, integrity_all]

- include: cron.yml
  tags: [cron, integrity_all]
