---

- import_tasks: vars.yml
  tags: [integrity_vars, always]

- import_tasks: debug.yml
  when: integrity_debug
  tags: [integrity_debug, always]

- import_tasks: packages.yml
  tags: integrity_packages

- import_tasks: source.yml
  tags: integrity_source

- import_tasks: copy.yml
  tags: integrity_copy

- import_tasks: configure.yml
  tags: integrity_configure

- import_tasks: cron.yml
  when: integrity_cron
  tags: integrity_cron

# EOF
...
