---

- name: Add {{ ansible_os_family }} specific variables
  include_vars: "{{ ansible_os_family }}.yml"
  tags: integrity_vars

- import_tasks: packages.yml
  tags: integrity_packages

- import_tasks: source.yml
  tags: integrity_source

- import_tasks: copy.yml
  tags: integrity_copy

- import_tasks: configure.yml
  tags: integrity_configure

- import_tasks: cron.yml
  when: integrity_cron
  tags: integrity_cron

# EOF
...
