---

- name: Import vars.yml
  ansible.builtin.import_tasks: vars.yml
  tags: [integrity_vars, always]

- name: Import debug.yml
  ansible.builtin.import_tasks: debug.yml
  when: integrity_debug | bool
  tags: integrity_debug

- name: Import pkg.yml
  ansible.builtin.import_tasks: pkg.yml
  when: integrity_install | bool
  tags: integrity_pkg

- name: Import source.yml
  ansible.builtin.import_tasks: source.yml
  tags: integrity_source

- name: Import copy.yml
  ansible.builtin.import_tasks: copy.yml
  tags: integrity_copy

- name: Import config.yml
  ansible.builtin.import_tasks: config.yml
  tags: integrity_config

- name: Import cron.yml
  ansible.builtin.import_tasks: cron.yml
  when: integrity_cron | bool
  tags: integrity_cron

# EOF
...
