---

- name: Add {{ ansible_os_family }} specific variables
  include_vars: "{{ ansible_os_family }}.yml"
  tags:
    - bsd_packages
    - bsd_ports
    - integrity_vars
    - integrity_all

- import_tasks: packages.yml
  tags:
    - bsd_packages
    - bsd_ports
    - linux_packages
    - integrity_packages
    - integrity_all

- import_tasks: source.yml
  tags:
    - integrity_source
    - integrity_all

- import_tasks: copy.yml
  tags:
    - integrity_copy
    - integrity_all

- import_tasks: configure.yml
  tags:
    - integrity_configure
    - integrity_all

- import_tasks: cron.yml
  tags:
    - integrity_cron
    - integrity_all

# EOF
...
