---

- name: Import vars.yml
  ansible.builtin.import_tasks: vars.yml
  tags: [integrity_vars, always]

- name: Import debug.yml
  ansible.builtin.import_tasks: debug.yml
  when: integrity_debug | bool
  tags: [integrity_debug, always]

- name: Import packages.yml
  ansible.builtin.import_tasks: packages.yml
  when: integrity_install | bool
  tags: integrity_packages

- name: Import source.yml
  ansible.builtin.import_tasks: source.yml
  tags: integrity_source

- name: Import copy.yml
  ansible.builtin.import_tasks: copy.yml
  tags: integrity_copy

- name: Import configure.yml
  ansible.builtin.import_tasks: configure.yml
  tags: integrity_configure

- name: Import cron.yml
  ansible.builtin.import_tasks: cron.yml
  when: integrity_cron | bool
  tags: integrity_cron

# EOF
...
