---

- name: "packages: Debug"
  ansible.builtin.debug:
    msg: "packages: ansible_os_family [{{ ansible_os_family }}]"
  when: integrity_debug|bool

# FreeBSD
- name: "packages: Install packages FreeBSD"
  ansible.builtin.pkgng:
    name: "{{ integrity_packages }}"
  register: result
  retries: "{{ freebsd_install_retries }}"
  until: result is succeeded
  delay: "{{ freebsd_install_delay }}"
  when:
    - ansible_os_family == "FreeBSD"
    - freebsd_install_method|lower == "packages"

- name: "packages: Install ports FreeBSD"
  ansible.builtin.portinstall:
    name: "{{ item }}"
    use_packages: "{{ freebsd_use_packages }}"
  loop: "{{ integrity_packages }}"
  register: result
  retries: "{{ freebsd_install_retries }}"
  until: result is succeeded
  delay: "{{ freebsd_install_delay }}"
  when:
    - ansible_os_family == "FreeBSD"
    - freebsd_install_method|lower == "ports"

# Linux
- name: "packages: Install packages Linux"
  ansible.builtin.package:
    name: "{{ item }}"
  loop: "{{ integrity_packages }}"
  register: result
  retries: "{{ linux_install_retries }}"
  until: result is succeeded
  delay: "{{ linux_install_delay }}"
  when: (ansible_os_family == "Debian") or
        (ansible_os_family == "RedHat")

# EOF
...
