---

- name: FreeBSD packages
  when:
    - ansible_os_family == 'FreeBSD'
    - freebsd_install_method|lower == 'packages'
  block:

    - name: "Pkg: Install FreeBSD packages"
      register: result
      community.general.pkgng:
        name: "{{ integrity_packages }}"
      retries: "{{ freebsd_install_retries }}"
      until: result is succeeded
      delay: "{{ freebsd_install_delay }}"

  rescue:

    - name: "Pkg: Rescue FreeBSD packages"
      ansible.builtin.fail:
        msg: |
          [ERR] task {{ ansible_failed_task.name }} failed.
          ansible_failed_task:
            {{ ansible_failed_task | to_yaml(indent=2) | indent(2) }}
          ansible_failed_result:
            {{ ansible_failed_result | to_yaml(indent=2) | indent(2) }}

- name: FreeBSD ports
  when:
    - ansible_os_family == 'FreeBSD'
    - freebsd_install_method|lower == 'ports'
  block:

    - name: "Pkg: Install FreeBSD ports"
      register: result
      community.general.portinstall:
        name: "{{ item }}"
        use_packages: "{{ freebsd_use_packages }}"
      loop: "{{ integrity_packages }}"
      retries: "{{ freebsd_install_retries }}"
      until: result is succeeded
      delay: "{{ freebsd_install_delay }}"

  rescue:

    - name: "Pkg: Rescue FreeBSD ports"
      ansible.builtin.fail:
        msg: |
          [ERR] task {{ ansible_failed_task.name }} failed.
          ansible_failed_task:
            {{ ansible_failed_task | to_yaml(indent=2) | indent(2) }}
          ansible_failed_result:
            {{ ansible_failed_result | to_yaml(indent=2) | indent(2) }}

- name: Linux packages
  when: ansible_os_family in integrity_supported_linux_family
  block:

    - name: "Pkg: Install Linux packages"
      register: result
      ansible.builtin.package:
        name: "{{ item }}"
      loop: "{{ integrity_packages }}"
      retries: "{{ linux_install_retries }}"
      until: result is succeeded
      delay: "{{ linux_install_delay }}"

  rescue:

    - name: "Pkg: Rescue Linux packages"
      ansible.builtin.fail:
        msg: |
          [ERR] task {{ ansible_failed_task.name }} failed.
          ansible_failed_task:
            {{ ansible_failed_task | to_yaml(indent=2) | indent(2) }}
          ansible_failed_result:
            {{ ansible_failed_result | to_yaml(indent=2) | indent(2) }}

# EOF
...
