---

- name: Create directory for the source code {{ integrity_source_dest }}
  file: >
    state="directory"
    path="{{ integrity_source_dest }}"

- name: Download sources from {{ integrity_source_url }}/{{ integrity_source_file }}
  get_url: >
    url="{{ integrity_source_url }}/{{ integrity_source_file }}"
    dest="{{ integrity_source_dest }}/integrity-{{ integrity_source_file }}"

- name: Extract sources to {{ integrity_source_dest }}
  unarchive: >
    src="{{ integrity_source_dest }}/integrity-{{ integrity_source_file }}"
    dest="{{ integrity_source_dest }}"
    remote_src="yes"
    extra_opts="--skip-old-files"
  changed_when: False
# TODO: Wait for fixed idempotent unarchive module
# https://github.com/ansible/ansible-modules-core/issues/3952
# https://github.com/ansible/ansible/issues/16276
# https://unix.stackexchange.com/questions/91135/error-handling-with-tar-and-keep-old-files-option

- name: Create symbolic link integrity to {{ integrity_source_dir }}
  file: >
    src="{{ integrity_source_dest }}/{{ integrity_source_dir }}"
    dest="{{ integrity_source_dest }}/integrity"
    state="link"
    force="yes"

- name: Which bash
  command: "which bash"
  register: integrity_which_bash
  changed_when: false

#- debug: msg="{{integrity_which_bash.stdout}}"

- name: Patch {{integrity_which_bash.stdout}} in {{ integrity_source_dest }}/integrity/integrity
  lineinfile: >
    dest="{{ integrity_source_dest }}/integrity/integrity"
    regexp="#!"
    line="#!{{integrity_which_bash.stdout}}"

# EOF
...
